# Generated by Django 4.0.3 on 2022-04-02 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.CharField(blank=True, default='https://i.imgur.com/VKXouC4.png', max_length=2000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('files', models.FileField(blank=True, null=True, upload_to='models/%Y/%m/$D/')),
                ('images', models.CharField(blank=True, default=None, max_length=2000, null=True)),
                ('text_content', models.TextField(blank=True, default=None, max_length=1000, null=True)),
                ('tags', models.TextField(blank=True, default=None, max_length=1000, null=True)),
                ('downloads', models.IntegerField()),
                ('type', models.CharField(default='STL', max_length=50)),
                ('account', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.account')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, default=None, null=True, upload_to='')),
                ('images', models.CharField(blank=True, default=None, max_length=2000, null=True)),
                ('text_content', models.CharField(max_length=3000)),
                ('title', models.CharField(max_length=100)),
                ('account', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.account')),
            ],
        ),
    ]
