# Generated by Django 4.0.3 on 2022-04-02 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.account'),
        ),
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='picture',
            field=models.CharField(blank=True, default='https://i.imgur.com/VKXouC4.png', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='files',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text_content',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='post',
            name='download',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_content',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(default='STL', max_length=50),
        ),
    ]
