# Generated by Django 4.0.3 on 2022-04-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='post',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
    ]
