# Generated by Django 4.0.3 on 2022-04-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='picture',
            field=models.FileField(blank=True, default='/media/models/accountImg/default.png', null=True, upload_to='models/accountImg'),
        ),
    ]
