# Generated by Django 4.0.3 on 2022-04-02 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_post_account_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='post',
        ),
    ]
