# Generated by Django 4.0.3 on 2022-04-03 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_post_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='files',
            new_name='model',
        ),
    ]
