# Generated by Django 4.0.3 on 2022-04-02 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.account'),
        ),
    ]
