# Generated by Django 4.0.3 on 2022-04-02 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_account_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.account'),
        ),
    ]
